### ISSUE TITLE
Validate song file

### ISSUE THREAD

**Issue by gsmendoza** [gsmendoza/songbook#1]
## Goal

I want to validate the YAML song file so that it's easier for me to debug the file if it's not valid.

### Preparation

* [x] Remove GenerateSongFiles later.

### Tasks

* [ ] Try https://github.com/voxpupuli/json-schema.
* [ ] Validate empty YAML file.
* [x] Handle YAML loading errors more gracefully.
* [ ] Rebase: remove `generate_song_files` require statement.
* [ ] Validate input path and output path.

### Stretch goals

* [ ] Check if input path is an existing file.
* [ ] Allow output_path to be a directory.
* [ ] Test if GenerateSongFile prints out errors
